[basic]
    debug: True
    model_name: "bayes-vnet_01"
    seed: 42
    n_classes: 6
    normalize: False
    volume_shape: (256, 256, 256)
    block_shape: (32, 32, 32)

[train]
    n_epochs: 50
    save_freq: "epoch"

[validation]

[test]
    n_samples: 1
