[basic]
    debug: True
    model_name: "brainy_t1"
    seed: 42
    n_classes: 50
    normalize: True
    volume_shape: (256, 256, 256)
    block_shape: (256, 256, 256)

[train]
    n_epochs: 200

[validation]

[test]
    n_samples: 1
