[basic]
    debug: True
    model_name: "20240513/brainy_t1"
    seed: 42
    n_classes: 6
    normalize: True
    volume_shape: (256, 256, 256)
    block_shape: (256, 256, 256)

[train]
    n_epochs: 500
    save_freq: "epoch"

[validation]

[test]
    n_samples: 1
