[basic]
    debug: True
    model_name: "brainy_t1"
    seed: 42
    n_classes: 50
    normalize: False
    volume_shape: (256, 256, 256)
    block_shape: (128, 128, 128)

[train]
    n_epochs: 1

[validation]

[test]
    n_samples: 1
