[basic]
    debug: True
    model_name: "kwyk_t0"
    seed: 42
    n_classes: 50
    normalize: False
    volume_shape: (256, 256, 256)
    block_shape: (32, 32, 32)

[train]
    n_epochs: 200

[validation]

[test]
    n_samples: 1
