[basic]
    debug: True
    model_name: "20240513/kwyk_t2"
    seed: 42
    n_classes: 50
    normalize: True
    volume_shape: (256, 256, 256)
    block_shape: (32, 32, 32)

[train]
    n_epochs: 250
    save_freq: "epoch"

[validation]

[test]
    n_samples: 1
