[basic]
    debug: True
    model_name: "test_decorator"
    seed: 42
    n_classes: 2
    normalize: True
    volume_shape: (256, 256, 256)
    block_shape: (256, 256, 256)

[train]
    n_epochs: 5
    save_freq: "epoch"

[validation]

[test]
    n_samples: 1
